### ISSUE TITLE
Setup and Install app on windows10

### ISSUE THREAD

**Issue by dororojames** [NMGRL/pychron#1832]
There are some error when I install pychron on window 10.
I can't run install_app() in install.py 
The ENV variable QT_API setting is different from linux. It might be 'pyqt' ONLY 
And the setup.py is incomplete, I can't import pychron.enviroment when I run launcher.py.

**Comment by jirhiker** [comment]
what error are you getting when you run `install.py`

The env variable QT_API depends on which version of Qt is installed, for recent installs its "pyqt5"

setup.py is not used in practice. It is only there for CI testing. 

Since a few environment variables need to be set I typically don't run `launcher.py` directly. Instead I use a .bat script that sets all the necessary variables and then calls `launcher.py`
