### ISSUE TITLE
Predefined Initializations

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#496]
How about for edit initialization, you offer a pyview, pyobama, and py jan option that will choose the correct plugin selections for these three most common setups.  This would help post-update setups for mortals.

**Comment by wcmcintosh** [comment]
Tested - seems to work well for selecting different configurations.  Thanks for doing this in spite of your reservations. There is still something funny going on here, though.  I selected data reduction and I think all of the default initialization parameters were selected correctly, and a restart was automatically requested and performed, but then the only user option was root, and the general and database preferences came up blank, requiring manual re-entry.  Trying to reset the user via View:Users did not work, I think because the database was not selected.I'm still a little uncertain on the various Pychron directories (Pychron versus Pychron_dev versus Pychrondata versus Pychrondata_dev versus Pychrondata_install.  Once the preferences was repopulated, Pychron data reduction seems to work fine, although view users is not responsive.  I need a tune up on the user login and multiple users check boxes in preferences.  I still think that a set of default preferences would be preferable to a blank selection.  That's my default philosophy.
